const $=q=>document.querySelector(q), main=$('#main');
const ASSET={harbor:'assets/grayharbor.jpg',tavern:'assets/scene-placeholder.svg',tower:'assets/scene-placeholder.svg',cellar:'assets/scene-placeholder.svg',undead:'assets/portrait-placeholder.svg',items:'assets/item-placeholder.svg'};
const races={
 human:{name:'人類',desc:'遍布西境的諸王國居民，文化多樣、適應力強。',hp:0,pow:0,def:0,trait:'適應者：沒有明顯弱項，能選擇最多基礎職業。',allow:['warrior','paladin','ranger','rogue','mage','cleric']},
 highElf:{name:'高等精靈',desc:'古老奧術城邦的後裔，重視學識與血統。',hp:-5,pow:2,def:0,trait:'奧術感知：部分魔法事件有額外解法。',allow:['warrior','paladin','rogue','mage','cleric','spellblade']},
 woodElf:{name:'森林精靈',desc:'生活於古林與邊境的氏族，擅長追蹤與伏擊。',hp:0,pow:1,def:1,trait:'林地步伐：追蹤與自然相關判定更有利。',allow:['warrior','ranger','rogue','mage','cleric']},
 dwarf:{name:'矮人',desc:'山城與地下堡壘的建造者，以鍛造、石工和氏族傳統聞名。',hp:10,pow:0,def:2,trait:'石之記憶：能辨識古代建築、符文與機關。',allow:['warrior','paladin','ranger','rogue','cleric','runeguard']},
 orc:{name:'獸人',desc:'來自東部高地的部族民族，重視誓言、祖靈與武勇。',hp:12,pow:2,def:0,trait:'鐵血：生命較高，威嚇與體魄相關選項更突出。',allow:['warrior','ranger','rogue','cleric','spiritcaller']},
 beastfolk:{name:'獸裔',desc:'擁有獸類特徵的多支族群，感官敏銳但常受城市居民戒備。',hp:0,pow:1,def:0,trait:'敏銳感官：更容易察覺伏擊、氣味與細微聲響。',allow:['warrior','ranger','rogue','mage','cleric']},
 undead:{name:'不死族',desc:'仍保有意志與記憶的復生者，被活人稱為「灰裔」。',hp:5,pow:1,def:1,trait:'亡者之軀：不易受恐懼與疾病影響，能感知死亡魔力；部分 NPC 對你戒備。',allow:['warrior','ranger','rogue','mage','cleric','gravebound']}
};
const classes={
 warrior:{name:'戰士',desc:'重甲近戰，以怒氣與防守反擊壓制敵人。',hp:130,pow:15,def:10,skill:'盾擊',skillText:'高傷害並強化本回合防守。',weapon:'舊軍刀'},
 paladin:{name:'聖騎士',desc:'以誓言與聖火作戰的重甲守護者。',hp:120,pow:13,def:11,skill:'聖光裁決',skillText:'造成傷害並治療自己。',weapon:'朝聖者戰槌'},
 ranger:{name:'遊俠',desc:'遠程獵手，擅長追蹤、伏擊與野外探索。',hp:105,pow:16,def:7,skill:'穿心箭',skillText:'有較高機率造成暴擊。',weapon:'榆木長弓'},
 rogue:{name:'盜賊',desc:'敏捷的機會主義者，能撬鎖、偷襲並利用地下人脈。',hp:100,pow:17,def:6,skill:'背刺',skillText:'敵人生命越低，傷害越高。',weapon:'缺口短劍'},
 mage:{name:'法師',desc:'奧術施法者，脆弱但具強大爆發能力。',hp:90,pow:20,def:4,skill:'霜火爆裂',skillText:'極高傷害，偶爾會失控反噬。',weapon:'學徒法杖'},
 cleric:{name:'牧師',desc:'研究信仰、秘儀與驅邪術的施法者。',hp:110,pow:12,def:8,skill:'祈禱之槌',skillText:'穩定傷害並獲得護佑。',weapon:'銀紋權杖'},
 spellblade:{name:'魔劍士',special:'高等精靈專屬',desc:'將奧術編入劍技的古老軍學傳承。',hp:105,pow:18,def:7,skill:'奧刃共鳴',skillText:'造成強力傷害並短暫削弱敵人。',weapon:'符文細劍'},
 runeguard:{name:'符文守衛',special:'矮人專屬',desc:'以刻印符文強化盾甲與武器的氏族守衛。',hp:138,pow:13,def:13,skill:'岩印猛擊',skillText:'造成傷害並大幅提高本回合防守。',weapon:'刻印戰斧'},
 spiritcaller:{name:'祖靈使',special:'獸人專屬',desc:'與祖先和元素靈溝通的部族施法者。',hp:118,pow:15,def:8,skill:'祖靈震擊',skillText:'造成傷害並有機率回復生命。',weapon:'祖靈骨杖'},
 gravebound:{name:'墓誓者',special:'不死族專屬',desc:'以死亡之力維持意志，介於戰士與死靈術士之間。',hp:125,pow:17,def:9,skill:'墓寒斬',skillText:'造成寒冷的死亡傷害，對受傷敵人更強。',weapon:'黑鐵墓刃'}
};
const baseState={version:2,created:false,name:'',raceId:'',classId:'',level:1,xp:0,gold:35,hp:100,location:'灰港',scene:'arrival',flags:{},quests:{},inventory:[{id:'bread',name:'乾硬麵包',type:'consumable',qty:2,desc:'回復 18 生命。'},{id:'potion',name:'初級治療藥水',type:'consumable',qty:1,desc:'回復 35 生命。'}],equipment:{weapon:null,armor:null,trinket:null},combat:null,log:[]};
let draftRace='human';
function clone(x){return JSON.parse(JSON.stringify(x))}
function migrate(raw){if(!raw)return clone(baseState);const n=Object.assign(clone(baseState),raw);n.version=2;n.flags=Object.assign({},raw.flags||{});n.quests=Object.assign({},raw.quests||{});n.inventory=Array.isArray(raw.inventory)?raw.inventory:clone(baseState.inventory);n.equipment=Object.assign({weapon:null,armor:null,trinket:null},raw.equipment||{});n.log=Array.isArray(raw.log)?raw.log:[];if(!n.raceId)n.raceId='human';if(n.quests.missing&&n.quests.missing.stage>=2)n.flags.ratsDefeated=true;if(!races[n.raceId])n.raceId='human';if(!classes[n.classId]&&n.created)n.classId='warrior';if(raw.version!==2&&n.combat)n.combat=null;return n}
function load(){try{return migrate(JSON.parse(localStorage.getItem('ashen-realms-save')))}catch(e){return clone(baseState)}}
let s=load();
function save(){localStorage.setItem('ashen-realms-save',JSON.stringify(s));renderHud()}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.classList.remove('show'),1700)}
function log(t){s.log.unshift(t);s.log=s.log.slice(0,50)}
function change(label,n){if(n)toast(`${label} ${n>0?'+':''}${n}`)}
function race(){return races[s.raceId]||races.human}
function cls(){return classes[s.classId]||classes.warrior}
function equipped(){return Object.values(s.equipment||{}).map(id=>s.inventory.find(x=>x.id===id)).filter(Boolean)}
function maxHp(){return Math.max(1,cls().hp+race().hp+(s.level-1)*10+equipped().reduce((a,x)=>a+(x.hp||0),0))}
function pow(){return cls().pow+race().pow+(s.level-1)*2+equipped().reduce((a,x)=>a+(x.pow||0),0)}
function def(){return cls().def+race().def+(s.level-1)+equipped().reduce((a,x)=>a+(x.def||0),0)}
function normalizeHp(){s.hp=Math.min(Math.max(0,Number(s.hp)||0),maxHp())}
function renderHud(){if(!s.created)return;normalizeHp();$('#hud').classList.remove('hidden');$('#nav').classList.remove('hidden');let hpPct=Math.round(s.hp/maxHp()*100),xpPct=Math.min(100,Math.round((s.xp%Math.max(100,s.level*100))/Math.max(100,s.level*100)*100));$('#hud').innerHTML=`<div class="spread"><div><b>${s.name}</b> <span class="pill">Lv.${s.level} ${race().name} · ${cls().name}</span><div class="muted">${s.location}</div></div><div class="legend">◆ ${s.gold}</div></div><div style="margin-top:10px"><div class="spread stat"><span>生命 ${s.hp}/${maxHp()}</span><span>攻擊 ${pow()} · 防禦 ${def()}</span></div><div class="bar"><div class="fill hp" style="width:${hpPct}%"></div></div><div class="bar" style="margin-top:5px"><div class="fill xp" style="width:${xpPct}%"></div></div></div>`}
function sceneImage(key){return key?`<img class="scene-img" src="${ASSET[key]}" alt="場景插圖" loading="eager" onerror="this.style.display='none'">`:''}
function boot(){if(!s.created)showCreate();else{normalizeHp();renderHud();showScene()}}
function showCreate(){const name=$('#nameInput')?.value||'';main.innerHTML=`<section class="card"><h2>建立你的冒險者</h2><p class="muted">西境曆 742 年。灰港的鐘聲已經七夜沒有停過，而你正乘著一艘漏水商船抵達這座邊境港城。</p><label>角色名稱</label><input id="nameInput" maxlength="16" placeholder="輸入名稱" value="${escapeHtml(name)}"><h3>選擇種族</h3><div class="grid">${Object.entries(races).map(([id,r])=>`<button class="select-card ${draftRace===id?'selected':''}" onclick="pickRace('${id}')"><b>${r.name}</b><span>${r.desc}</span><div class="race-note">${r.trait}</div></button>`).join('')}</div><div class="divider"></div><h3>選擇職業</h3><p class="muted">部分職業受到種族文化、宗教或生理限制。被鎖定的職業仍會顯示原因。</p><div class="grid">${Object.entries(classes).map(([id,c])=>{const ok=races[draftRace].allow.includes(id);return `<button class="select-card" ${ok?`onclick="chooseClass('${id}')"`:'disabled'}><b>${c.name}</b><span>${c.desc}</span><div class="stat" style="margin-top:7px">生命 ${c.hp+races[draftRace].hp} · 攻擊 ${c.pow+races[draftRace].pow} · 防禦 ${c.def+races[draftRace].def}</div>${c.special?`<div class="tag" style="margin-top:7px">${c.special}</div>`:''}${ok?'':`<div class="lock">無法選擇：${lockReason(draftRace,id)}</div>`}</button>`}).join('')}</div></section>`}
function pickRace(id){const name=$('#nameInput')?.value||'';draftRace=id;showCreate();$('#nameInput').value=name}
function lockReason(rid,cid){if(cid==='gravebound')return '只有不死族能承受墓誓。';if(cid==='runeguard')return '符文守衛只傳授給矮人氏族。';if(cid==='spiritcaller')return '祖靈使必須接受獸人部族的祖靈儀式。';if(cid==='spellblade')return '魔劍術由高等精靈城邦嚴格守秘。';if(cid==='paladin'&&rid==='undead')return '聖火拒絕已死之軀。';return '此種族沒有這項職業傳統。'}
function chooseClass(id){if(!races[draftRace].allow.includes(id))return;let name=$('#nameInput').value.trim()||'無名旅人';s=clone(baseState);s.created=true;s.name=name;s.raceId=draftRace;s.classId=id;s.hp=maxHp();s.inventory.push({id:'starter',name:classes[id].weapon,type:'weapon',pow:3,desc:'陪你踏入灰港的第一件武器。'});s.equipment.weapon='starter';log(`${name}，一名${races[draftRace].name}${classes[id].name}，抵達灰港。`);save();showScene();toast(`角色建立：${races[draftRace].name} ${classes[id].name}`)}
const scenes={
 arrival(){let extra=s.raceId==='undead'?'你把兜帽拉低；巡查的守衛在你身上多停留了幾秒。':'';return{title:'鹽霧中的灰港',img:'harbor',text:`港口被低沉的鐘聲籠罩。灰斗篷守衛正在檢查旅客，一名老婦人緊抓著失蹤告示。遠處，斷裂鐘塔像黑色手指指向天空。${extra}`,choices:[['詢問守衛最近發生了什麼','guard'],['查看失蹤告示','notice'],['前往「斷錨酒館」','tavern'],['走向舊鐘塔附近','towerRoad']]}},
 guard(){let u=s.raceId==='undead'?'米菈看見你蒼白的手腕，沒有拔劍，只淡淡補了一句：「只要你守灰港的法律，我就不管你是不是死人。」':'';return{title:'城衛隊長米菈',img:'harbor',text:`「第三個了。」女隊長壓低聲音。「三週內三個人失蹤，最後都有人看見他們往舊鐘塔走。議會說是逃兵或醉鬼，我不信。」${u}`,choices:[['我可以調查。','acceptQuest'],['你願意付多少？','bargain'],['暫時不想惹麻煩。','arrival']]}},
 notice(){return{title:'被雨水浸透的告示',img:'harbor',text:'紙上畫著年輕抄寫員歐林：失蹤七日，最後出現於市場北街。告示角落有一個不屬於官方的墨色符號——像被劈成兩半的眼睛。',choices:[['記住「裂眼」符號','markSigil'],['去問酒館的人','tavern'],['找城衛隊長','guard']]}},
 tavern(){return{title:'斷錨酒館',img:'tavern',text:'廉價麥酒、濕羊毛與海鹽氣味混在一起。吟遊詩人停下彈奏，角落傭兵正低聲爭吵；酒保哈洛見你盯著失蹤告示，把杯子擦得更用力。',choices:[['向酒保打聽失蹤者','bartender'],['偷聽角落傭兵','mercs'],['花 3 金幣喝一杯黑麥酒','buyAle'],['返回港口','arrival']]}},
 bartender(){return{title:'酒保哈洛',img:'tavern',text:'「我只賣酒，不賣麻煩。」哈洛沒有看你。「不過那幾個失蹤的人……都問過舊鐘塔下面的路。」',choices:[['繼續追問','bartenderPress'],['不再逼他','tavern']]}},
 towerRoad(){let after=s.flags.ratsDefeated?'通往鐘塔的側門已經被你清理過，原本的鼠群不會再次出現。':'';return{title:'舊鐘塔外圍',img:'tower',text:`雨水沿著破損鐘塔的石牆流下。側牆附近有被拖行的痕跡，半埋的石階通往一扇鏽蝕鐵門。${after}`,choices:[['檢查地面痕跡','track'],[s.flags.ratsDefeated?'再次進入鐘塔':'進入鐘塔','towerEntry'],['返回灰港','arrival']]}},
 towerDeep(){let hint=s.raceId==='dwarf'||s.classId==='runeguard'?'你看出地窖門不是鐘塔原建築的一部分，而是後來由另一批石匠封上的。':'';return{title:'舊鐘塔內部',img:'tower',text:`斷裂鐘繩垂在中央，石地板下傳來含糊低語。鼠群巢穴後方露出一道向下石階，冷霧正從地窖門縫湧出。${hint}`,choices:[['檢查地窖門','cellarGate'],['回灰港整備','arrival']]}},
 cellarGate(){let opts=[];if(s.flags.cellarKey)opts.push(['使用生鏽的地窖鑰匙','openCellar']);if(s.classId==='rogue')opts.push(['撬開老鎖【盜賊】','pickCellar']);if(s.raceId==='dwarf'||s.classId==='runeguard')opts.push(['從石框弱點卸下鎖座【矮人】','dwarfCellar']);opts.push(['強行撬門','forceCellar'],['返回鐘塔上層','towerDeep']);return{title:'封死的地窖門',img:'tower',text:'鐵門上有三層不同年代的鎖痕。最新的一道鎖仍沾著油，說明最近有人頻繁使用。門後傳來斷續的金屬拖曳聲。',choices:opts}},
 cellarCrossroads(){let extra=s.raceId==='undead'?'你感覺到一股只屬於亡者的寒意從祭壇方向傳來。':'';return{title:'鐘塔地窖：岔路',img:'cellar',text:`地下拱廊比鐘塔本身古老得多。左側是關押過人的鐵籠區，右側通往掛滿裂眼布幔的祭壇廳。地面留著新的腳印。${extra}`,choices:[['搜索囚籠區','cells'],['沿裂眼標記前進','ritualHall'],['返回鐘塔','towerDeep']]}},
 cells(){let done=s.flags.survivorFound?'被救出的傷者已經離開，空籠裡只留下撕裂的繩結。':'最裡面的鐵籠傳來微弱敲擊聲。一名失蹤的碼頭工仍活著，他說「披灰面具的人」把歐林帶去了祭壇。';let choices=s.flags.survivorFound?[['搜索附近殘留物','searchCells'],['返回岔路','cellarCrossroads']]:[['救出碼頭工','rescueSurvivor'],['先搜索附近','searchCells'],['返回岔路','cellarCrossroads']];return{title:'廢棄囚籠',img:'cellar',text:done,choices}},
 ritualHall(){let special=s.raceId==='undead'?'你不需要閱讀符文，就知道這不是召魂術——儀式是在把某種東西「固定」在活人身上。':s.classId==='mage'||s.classId==='spellblade'?'奧術殘留顯示這是一種強行綁定靈魂的儀式。':'祭壇旁的骨片與黑蠟都刻著裂眼標記。';let choices=[];if(!s.flags.acolyteDefeated)choices.push(['逼近祭壇','fightAcolyte']);else if(!s.flags.bossDefeated)choices.push(['深入祭壇後方','fightWarden']);else choices.push(['檢查已沉寂的祭壇','dungeonCleared']);choices.push(['退回岔路','cellarCrossroads']);return{title:'裂眼祭壇',img:'cellar',text:`高聳石柱間吊著空鐵籠，祭壇上燃著不自然的冷焰。${special}`,choices}},
 dungeonCleared(){return{title:'沉默的鐘塔',img:'cellar',text:'裂眼儀式停止後，鐘塔下方第一次真正安靜下來。你在祭壇後找到歐林留下的筆記：失蹤案似乎只是更大事件的入口，而「裂眼」並不只存在於灰港。',choices:[['帶著證據返回米菈身邊','reportQuest'],['繼續探索地窖','cellarCrossroads']]}},
 epilogue(){return{title:'第一章：餘響',img:'harbor',text:'米菈讀完歐林的筆記，久久沒有說話。她把一枚城衛徽記推到你面前：「如果裂眼真的在別處也有據點，我們會需要一個不屬於議會的人去查。」灰港主線第一章至此暫告一段落，但地窖與城市仍可繼續探索。',choices:[['回到灰港自由探索','arrival']]}}
};
function showScene(){closeModal();if(s.combat){renderCombat();return}const fn=scenes[s.scene]||scenes.arrival,o=fn();main.innerHTML=`<section class="card hero">${sceneImage(o.img)}<div class="hero-copy"><h2>${o.title}</h2><p class="story">${o.text}</p><div class="choices">${o.choices.map(([t,a])=>`<button onclick="act('${a}')">${t}</button>`).join('')}</div></div></section>`}
function ensureQuest(){if(!s.quests.missing)s.quests.missing={name:'鐘塔下的失蹤者',stage:1,desc:'調查灰港近期的失蹤案。'}}
function act(a){
 if(['arrival','guard','notice','tavern','bartender','towerRoad','towerDeep','cellarGate','cellarCrossroads','cells','ritualHall','dungeonCleared','epilogue'].includes(a)){s.scene=a;save();showScene();return}
 if(a==='acceptQuest'){ensureQuest();s.gold+=10;change('金幣',10);log('接下任務：鐘塔下的失蹤者。');s.scene='towerRoad'}
 if(a==='bargain'){ensureQuest();let chance=s.raceId==='human'?0.65:0.5,ok=Math.random()<chance;if(ok){s.gold+=20;change('金幣',20);log('你成功讓米菈提高訂金。')}else log('米菈拒絕討價還價。');s.scene='towerRoad'}
 if(a==='markSigil'){s.flags.sigil=true;log('你記下了「裂眼」符號。');toast('獲得線索：裂眼');s.scene='tavern'}
 if(a==='mercs'){s.flags.towerNoise=true;log('你聽見傭兵提到鐘塔下面有人夜間搬運箱籠。');toast('獲得線索：地下門');s.scene='tavern'}
 if(a==='bartenderPress'){let bonus=s.classId==='rogue'?0.3:0;let ok=Math.random()<.48+bonus;if(ok&&!s.flags.cellarKey){s.flags.cellarKey=true;s.inventory.push({id:'cellarKey',name:'生鏽的地窖鑰匙',type:'quest',desc:'哈洛偷偷塞給你的鑰匙。'});toast('獲得：地窖鑰匙');log('哈洛承認有人利用鐘塔地窖進出。')}else if(!ok)log('哈洛拒絕再說任何話。');s.scene='towerRoad'}
 if(a==='buyAle'){if(s.gold>=3){s.gold-=3;let h=Math.min(8,maxHp()-s.hp);s.hp+=h;change('金幣',-3);change('生命',h);log('你喝了一杯味道可疑的黑麥酒。')}else toast('金幣不足');s.scene='tavern'}
 if(a==='track'){let good=['ranger','rogue'].includes(s.classId)||s.raceId==='woodElf'||s.raceId==='beastfolk';let chance=good?.85:.5;if(Math.random()<chance){s.flags.track=true;log('你發現拖行痕跡與少量黑蠟通往鐘塔側牆。');toast('獲得線索：拖行痕跡')}else log('雨水沖掉了大部分痕跡。');s.scene='towerRoad'}
 if(a==='towerEntry'){ensureQuest();if(s.flags.ratsDefeated){s.location='舊鐘塔';s.scene='towerDeep'}else{startCombat(enemy('rats'));return}}
 if(['openCellar','pickCellar','dwarfCellar'].includes(a)){s.flags.cellarOpen=true;s.location='鐘塔地窖';s.quests.missing.stage=Math.max(3,s.quests.missing.stage||1);s.quests.missing.desc='深入鐘塔地窖，尋找失蹤者與裂眼組織的線索。';log('你打開了封死的地窖門。');s.scene='cellarCrossroads'}
 if(a==='forceCellar'){let strong=s.classId==='warrior'||s.raceId==='orc';let ok=Math.random()<(strong?.8:.42);if(ok){s.flags.cellarOpen=true;s.location='鐘塔地窖';log('你用蠻力撬開了地窖門。');s.scene='cellarCrossroads'}else{let hurt=Math.min(5,Math.max(0,s.hp-1));s.hp-=hurt;log(`鐵門紋絲不動，你在嘗試中損失 ${hurt} 生命。`);s.scene='cellarGate'}}
 if(a==='rescueSurvivor'){s.flags.survivorFound=true;s.quests.missing.stage=Math.max(4,s.quests.missing.stage||1);s.quests.missing.desc='你救出一名失蹤者；歐林被帶往裂眼祭壇。';s.xp+=25;change('經驗',25);log('你救出碼頭工並得知歐林被帶往祭壇。');levelCheck();s.scene='cells'}
 if(a==='searchCells'){if(!s.flags.cellsLoot){s.flags.cellsLoot=true;s.inventory.push({id:'potion2',name:'封蠟治療藥水',type:'consumable',qty:1,desc:'回復 35 生命。'});toast('找到：治療藥水');log('你在破箱裡找到一瓶尚可使用的藥水。')}else log('囚籠區已被你搜索過。');s.scene='cells'}
 if(a==='fightAcolyte'){startCombat(enemy('acolyte'));return}
 if(a==='fightWarden'){startCombat(enemy('warden'));return}
 if(a==='reportQuest'){if(!s.flags.reported){s.flags.reported=true;s.gold+=55;s.xp+=80;s.inventory.push({id:'guardSeal',name:'灰港城衛徽記',type:'trinket',def:2,desc:'米菈交給你的私人徽記。裝備後防禦 +2。'});change('金幣',55);log('完成任務：鐘塔下的失蹤者。');s.quests.missing.stage=6;s.quests.missing.desc='你摧毀了鐘塔下的裂眼據點，並把證據交給米菈。';levelCheck()}s.scene='epilogue'}
 save();showScene()
}
function enemy(id){return clone({rats:{id:'rats',name:'腐化鼠群',hp:56,maxHp:56,pow:11,def:2,xp:35,gold:8,onWin:'rats'},acolyte:{id:'acolyte',name:'裂眼侍從',hp:78,maxHp:78,pow:14,def:5,xp:55,gold:13,onWin:'acolyte'},warden:{id:'warden',name:'鐘下守衛',hp:132,maxHp:132,pow:17,def:8,xp:110,gold:28,onWin:'warden'}}[id])}
function startCombat(e){s.combat=e;log(`遭遇：${e.name}。`);save();renderCombat()}
function dmg(base,armor){return Math.max(1,Math.round(base*(.85+Math.random()*.3)-armor*.45))}
function combatFlavor(){return{warrior:'你穩住重心，等待對方暴露破綻。',paladin:'你低聲誦念誓詞，聖徽微微發熱。',ranger:'你控制呼吸，尋找最佳射線。',rogue:'你繞向陰影，等待最短的出手機會。',mage:'奧術在指尖聚集，空氣輕微震動。',cleric:'你握緊權杖，祈禱聲壓過地底低鳴。',spellblade:'符文沿劍脊亮起，你把咒式壓進下一次斬擊。',runeguard:'盾面石紋發亮，腳下彷彿與地基連成一體。',spiritcaller:'你喚起祖靈的回聲，空氣帶上荒原氣息。',gravebound:'墓寒沿著武器爬升，你的亡者之軀毫不顫抖。'}[s.classId]||'你準備迎戰。'}
function renderCombat(){let e=s.combat,pct=Math.max(0,Math.round(e.hp/e.maxHp*100));main.innerHTML=`<section class="card"><div class="tag">戰鬥</div><h2 style="margin-top:8px">${e.name}</h2><div class="spread stat"><span>敵人生命 ${e.hp}/${e.maxHp}</span><span>威脅 ${e.pow}</span></div><div class="bar"><div class="fill enemy" style="width:${pct}%"></div></div><div class="divider"></div><p>${combatFlavor()}</p><div class="choices"><button class="primary" onclick="combatTurn('attack')">普通攻擊</button><button onclick="combatTurn('skill')">${cls().skill} — ${cls().skillText}</button><button onclick="combatTurn('potion')">使用治療藥水</button><button class="danger" onclick="combatTurn('flee')">嘗試撤退</button></div></section><section class="card"><h3>戰鬥紀錄</h3><div class="log">${s.log.slice(0,10).map(x=>`<div>• ${x}</div>`).join('')}</div></section>`}
function combatTurn(type){let e=s.combat,guard=0,enemyWeaken=0;if(type==='flee'){if(e.id==='warden'){toast('守衛封住了退路');return}if(Math.random()<.45){log('你成功脫離戰鬥。');s.combat=null;s.scene=e.id==='rats'?'towerRoad':'cellarCrossroads';save();showScene();return}else log('退路被封住了。')}
 else if(type==='potion'){let it=s.inventory.find(x=>x.type==='consumable'&&x.id.includes('potion')&&x.qty>0);if(!it){toast('沒有治療藥水');return}it.qty--;let heal=Math.min(35,maxHp()-s.hp);s.hp+=heal;log(`你使用治療藥水，回復 ${heal} 生命。`);change('生命',heal)}
 else{let bonus=type==='skill'?6:0,hit=dmg(pow()+bonus,e.def);if(type==='skill'&&s.classId==='ranger'&&Math.random()<.38)hit*=2;if(type==='skill'&&['rogue','gravebound'].includes(s.classId))hit+=Math.round((1-e.hp/e.maxHp)*11);if(type==='skill'&&s.classId==='mage'&&Math.random()<.14){s.hp=Math.max(1,s.hp-6);log('失控奧術反噬了你 6 點生命。')}if(type==='skill'&&s.classId==='paladin'){let h=Math.min(10,maxHp()-s.hp);s.hp+=h}if(type==='skill'&&s.classId==='spiritcaller'&&Math.random()<.5){let h=Math.min(8,maxHp()-s.hp);s.hp+=h}if(type==='skill'&&['warrior','runeguard','cleric'].includes(s.classId))guard=s.classId==='runeguard'?7:4;if(type==='skill'&&s.classId==='spellblade')enemyWeaken=3;e.hp=Math.max(0,e.hp-hit);log(`${type==='skill'?cls().skill:'攻擊'}造成 ${hit} 傷害。`)}
 if(e.hp<=0){winCombat();return}let taken=dmg(Math.max(1,e.pow-enemyWeaken),def()+guard);s.hp=Math.max(0,s.hp-taken);log(`${e.name} 對你造成 ${taken} 傷害。`);if(s.hp<=0){s.hp=Math.ceil(maxHp()*.55);s.gold=Math.max(0,s.gold-8);s.combat=null;s.scene='arrival';s.location='灰港';log('你在城衛哨站醒來，失去了一些金幣。');toast('你被擊倒了');save();showScene();return}save();renderCombat()}
function winCombat(){let e=s.combat;s.xp+=e.xp;s.gold+=e.gold;log(`擊敗 ${e.name}。獲得 ${e.xp} 經驗與 ${e.gold} 金幣。`);let ev=e.onWin;s.combat=null;if(ev==='rats'){s.flags.ratsDefeated=true;s.location='舊鐘塔';ensureQuest();s.quests.missing.stage=2;s.quests.missing.desc='鐘塔內的鼠群受到異常力量腐化。深入地窖尋找失蹤者。';if(!s.inventory.some(x=>x.id==='fang'))s.inventory.push({id:'fang',name:'染黑的鼠牙',type:'trinket',def:1,desc:'不自然地冰冷。裝備後防禦 +1。'});log('鼠群不再堵住入口；你找到刻著裂眼符號的骨片。');s.scene='towerDeep'}if(ev==='acolyte'){s.flags.acolyteDefeated=true;if(!s.inventory.some(x=>x.id==='riftShard'))s.inventory.push({id:'riftShard',name:'裂眼骨片',type:'quest',desc:'祭壇侍從攜帶的刻印骨片。'});s.scene='ritualHall';log('侍從倒下後，祭壇後方的暗門緩緩打開。')}if(ev==='warden'){s.flags.bossDefeated=true;ensureQuest();s.quests.missing.stage=5;s.quests.missing.desc='裂眼祭壇已被摧毀。帶著歐林的筆記回去找米菈。';if(!s.inventory.some(x=>x.id==='bellCharm'))s.inventory.push({id:'bellCharm',name:'沉鐘碎片',type:'trinket',pow:2,def:1,desc:'第一個地下城首領留下的稀有飾品：攻擊 +2、防禦 +1。'});s.scene='dungeonCleared';log('鐘下守衛被擊敗，整座地窖的低語逐漸消失。')}levelCheck();save();showScene()}
function levelCheck(){let up=false;while(s.xp>=s.level*100){s.level++;up=true;log(`升級！你現在是 ${s.level} 級。`)}if(up){s.hp=maxHp();toast(`升級至 Lv.${s.level}`)}}
function showCharacter(){let portrait=s.raceId==='undead'?`<img class="portrait" src="${ASSET.undead}" alt="不死族角色概念圖" onerror="this.style.display='none'">`:'';openModal(`<h2>${s.name}</h2><p class="muted">Lv.${s.level} ${race().name} · ${cls().name}</p>${portrait}<div class="notice">${race().trait}</div><div class="grid" style="margin-top:12px"><div class="item"><div class="muted">生命</div><div class="kpi">${s.hp}/${maxHp()}</div></div><div class="item"><div class="muted">攻擊</div><div class="kpi">${pow()}</div></div><div class="item"><div class="muted">防禦</div><div class="kpi">${def()}</div></div><div class="item"><div class="muted">經驗</div><div class="kpi">${s.xp}</div></div></div><div class="divider"></div><h3>職業能力</h3><p><b>${cls().skill}</b><br><span class="muted">${cls().skillText}</span></p><h3>裝備</h3>${['weapon','armor','trinket'].map(slot=>{let it=s.inventory.find(x=>x.id===s.equipment[slot]);return `<div class="item"><span class="muted">${{weapon:'武器',armor:'護甲',trinket:'飾品'}[slot]}</span><br>${it?it.name:'— 空 —'}</div>`}).join('')}`)}
function showInventory(){openModal(`<h2>背包</h2><img class="concept" src="${ASSET.items}" alt="道具概念圖" onerror="this.style.display='none'"><p class="muted">裝備與任務物品可能改變數值或開啟特殊選項。</p>${s.inventory.map((it,i)=>`<div class="item"><div class="spread"><b>${it.name}${it.qty?` ×${it.qty}`:''}</b><span class="tag">${it.type}</span></div><div class="muted">${it.desc||''}</div>${['weapon','armor','trinket'].includes(it.type)?`<button style="margin-top:8px" onclick="equip(${i})">裝備</button>`:''}</div>`).join('')}`)}
function equip(i){let it=s.inventory[i];if(!['weapon','armor','trinket'].includes(it.type))return;s.equipment[it.type]=it.id;normalizeHp();save();toast(`已裝備：${it.name}`);showInventory()}
function showJournal(){let qs=Object.values(s.quests);openModal(`<h2>任務日誌</h2>${qs.length?qs.map(q=>`<div class="item"><b>${q.name}</b><div class="muted">${q.desc}</div><div class="tag" style="margin-top:7px">階段 ${q.stage}</div></div>`).join(''):'目前沒有進行中的任務。'}`)}
function showMenu(){openModal(`<h2>系統</h2><p>版本 <b>v0.2</b></p><p class="muted">本版本加入：7 種族、種族職業限制、4 個種族專屬職業、不死族、舊存檔遷移、鐘塔地窖擴建、首領戰，以及第一批正式場景素材。</p><div class="choices"><button onclick="save();toast('已儲存')">立即儲存</button><button class="danger" onclick="resetGame()">刪除存檔並重新開始</button></div>`)}
function openModal(html){$('#sheet').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function resetGame(){if(confirm('確定要刪除存檔嗎？')){localStorage.removeItem('ashen-realms-save');location.reload()}}
function escapeHtml(t){return String(t).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
boot();